### PR TITLE
Tesseract text detection

### PR DESCRIPTION
**Pull request by pevogam**
This branch adds (py)tesseract-only text detection backend and
applies some recursive region tricks to improve it for large enough
screen regions.

### CODE REVIEW

**Comment by pevogam** [comment]
@miqsoft I see you are experimenting with OCR in which case you might be interested to try out this branch and in particular OCR text detection using pytesseract.

**Comment by miqsoft** [comment]
> @miqsoft I see you are experimenting with OCR in which case you might be interested to try out this branch and in particular OCR text detection using pytesseract.

Thanks - I will have a look into it and try it out the following days.

**Comment by miqsoft** [comment]
Hey, 
since some of my tests failed I created an complex example, where we can see that pytesseract misses a lot of text.
I tried around with the settings but could not fix it easily. Any ideas? Or is this to be expected?

tdetect backend: pytesseract
ex_default_pytess

tdetect backend: contours
ex_default_contour

**Comment by pevogam** [comment]
> since some of my tests failed I created an complex example, where we can see that pytesseract misses a lot of text.
> I tried around with the settings but could not fix it easily. Any ideas? Or is this to be expected?

As any kind of backend Tesseract's own text detection is unfortunately far from perfect and typically needs extra tweaking on a case by case basis. I have one idea to add some custom preprocessing before tesseract does the text detection but given that tesseract does its own preprocessing I am not sure how helpful this could be. In any case, once I have a branch ready you could try it out if you want or if you have any good suggestions on preprocessing that would improve the native text detection of Tesseract, let me know.

**Comment by pevogam** [comment]
I have added at least one more [improvement](49e70920915cae4342ccb8824f8f4dc71a5c688a) on top which allows for a thresholding + line segment removal technique as some additional preprocessing to improve the text detection results. However, the branch was blocked for quite a while now so let's simply merge it to enable the functionality for everyone and look into further refinements of the native tesseract text detection (within tesseract's own repo or via downstream customization here) based on use cases and overall user demand.

**Pull request merged**
